default_platform(:ios)

platform :ios do
  desc "Push a new beta build to Apple TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "Moon.xcodeproj")
    build_app(workspace: "Moon.xcworkspace", scheme: "Moon")
    upload_to_testflight
  end
end
