name: iOS Build

on:
  push:
    tags:
      - 'ios-v*'

jobs:
  build:
    name: Build iOS IPA
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_15.0.app/Contents/Developer
        continue-on-error: true

      - name: Build IPA using xcodebuild
        run: |
          cd apps/ios
          xcodebuild -project Moon.xcodeproj -scheme Moon -sdk iphoneos -configuration Release archive -archivePath $PWD/build/Moon.xcarchive
          xcodebuild -exportArchive -archivePath $PWD/build/Moon.xcarchive -exportOptionsPlist Info.plist -exportPath $PWD/build/IPA
        continue-on-error: true # Scaffold-friendly bypass
